title:        Qiao Gao's blog
tagline:      'Hyde, a Jekyll theme'
description:  'Hi, welcome to my blog. As a graduate student on electrical engineering, I feel interested in any new techniques and some other fascinating stuffs. Please be free to communicate with me.'
url:          http://www.qiaogao.net
version:      1.1.1
author:       Qiao Gao
  name:       'Qiao Gao'
  email:      'gqplus2@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
